# Surah metadata used for offline navigation. Counts follow the standard 114-surah / 6236-ayah numbering.
SURAHS = [
    (1, 'al-fātiḥah', 'The Opening', 7),
    (2, 'al-baqarah', 'The Cow', 286),
    (3, 'āl ʿimrān', 'The Family of Imran', 200),
    (4, 'al-nisāʾ', 'The Women', 176),
    (5, 'al-māʾidah', 'The Table Spread', 120),
    (6, 'al-anʿām', 'The Cattle', 165),
    (7, 'al-aʿrāf', 'The Heights', 206),
    (8, 'al-anfāl', 'The Spoils of War', 75),
    (9, 'al-tawbah', 'The Repentance', 129),
    (10, 'yūnus', 'Jonah', 109),
    (11, 'hūd', 'Hud', 123),
    (12, 'yūsuf', 'Joseph', 111),
    (13, 'al-raʿd', 'The Thunder', 43),
    (14, 'ibrāhīm', 'Abraham', 52),
    (15, 'al-ḥijr', 'The Rocky Tract', 99),
    (16, 'al-naḥl', 'The Bees', 128),
    (17, 'al-isrāʾ', 'The Night Journey', 111),
    (18, 'al-kahf', 'The Cave', 110),
    (19, 'maryam', 'Mary', 98),
    (20, 'ṭā hā', 'Ta-Ha', 135),
    (21, 'al-anbiyāʾ', 'The Prophets', 112),
    (22, 'al-ḥajj', 'The Pilgrimage', 78),
    (23, 'al-muʾminūn', 'The Believers', 118),
    (24, 'al-nūr', 'The Light', 64),
    (25, 'al-furqān', 'The Criterion', 77),
    (26, 'al-shuʿarāʾ', 'The Poets', 227),
    (27, 'al-naml', 'The Ants', 93),
    (28, 'al-qaṣaṣ', 'The Stories', 88),
    (29, 'al-ʿankabūt', 'The Spider', 69),
    (30, 'al-rūm', 'The Romans', 60),
    (31, 'luqmān', 'Luqman', 34),
    (32, 'al-sajdah', 'The Prostration', 30),
    (33, 'al-aḥzāb', 'The Combined Forces', 73),
    (34, 'sabaʾ', 'Sheba', 54),
    (35, 'fāṭir', 'The Originator', 45),
    (36, 'yā sīn', 'Ya-Sin', 83),
    (37, 'al-ṣāffāt', 'Those Ranged in Ranks', 182),
    (38, 'ṣād', 'Sad', 88),
    (39, 'al-zumar', 'The Groups', 75),
    (40, 'ghāfir', 'The Forgiver', 85),
    (41, 'fuṣṣilat', 'Explained in Detail', 54),
    (42, 'al-shūrā', 'Consultation', 53),
    (43, 'al-zukhruf', 'The Gold Adornment', 89),
    (44, 'al-dukhān', 'The Smoke', 59),
    (45, 'al-jāthiyah', 'The Crouching', 37),
    (46, 'al-aḥqāf', 'The Wind-Curved Sandhills', 35),
    (47, 'muḥammad', 'Muhammad', 38),
    (48, 'al-fatḥ', 'The Victory', 29),
    (49, 'al-ḥujurāt', 'The Rooms', 18),
    (50, 'qāf', 'Qaf', 45),
    (51, 'al-dhāriyāt', 'The Scatterers', 60),
    (52, 'al-ṭūr', 'The Mount', 49),
    (53, 'al-najm', 'The Star', 62),
    (54, 'al-qamar', 'The Moon', 55),
    (55, 'al-raḥmān', 'The Most Gracious', 78),
    (56, 'al-wāqiʿah', 'The Event', 96),
    (57, 'al-ḥadīd', 'The Iron', 29),
    (58, 'al-mujādilah', 'The Pleading Woman', 22),
    (59, 'al-ḥashr', 'The Gathering', 24),
    (60, 'al-mumtaḥanah', 'The Woman to be Examined', 13),
    (61, 'al-ṣaff', 'The Row', 14),
    (62, 'al-jumuʿah', 'Friday', 11),
    (63, 'al-munāfiqūn', 'The Hypocrites', 11),
    (64, 'al-taghābun', 'Mutual Loss and Gain', 18),
    (65, 'al-ṭalāq', 'The Divorce', 12),
    (66, 'al-taḥrīm', 'The Prohibition', 12),
    (67, 'al-mulk', 'Dominion', 30),
    (68, 'al-qalam', 'The Pen', 52),
    (69, 'al-ḥāqqah', 'The Inevitable', 52),
    (70, 'al-maʿārij', 'The Ways of Ascent', 44),
    (71, 'nūḥ', 'Noah', 28),
    (72, 'al-jinn', 'The Jinn', 28),
    (73, 'al-muzzammil', 'The Enshrouded One', 20),
    (74, 'al-muddaththir', 'The Cloaked One', 56),
    (75, 'al-qiyāmah', 'The Resurrection', 40),
    (76, 'al-insān', 'Man', 31),
    (77, 'al-mursalāt', 'Those Sent Forth', 50),
    (78, 'al-nabaʾ', 'The Great News', 40),
    (79, 'al-nāziʿāt', 'Those Who Pull Out', 46),
    (80, 'ʿabasa', 'He Frowned', 42),
    (81, 'al-takwīr', 'The Overthrowing', 29),
    (82, 'al-infiṭār', 'The Cleaving', 19),
    (83, 'al-muṭaffifīn', 'Those Who Deal in Fraud', 36),
    (84, 'al-inshiqāq', 'The Splitting Open', 25),
    (85, 'al-burūj', 'The Mansions of the Stars', 22),
    (86, 'al-ṭāriq', 'The Night-Comer', 17),
    (87, 'al-aʿlā', 'The Most High', 19),
    (88, 'al-ghāshiyah', 'The Overwhelming', 26),
    (89, 'al-fajr', 'The Dawn', 30),
    (90, 'al-balad', 'The City', 20),
    (91, 'al-shams', 'The Sun', 15),
    (92, 'al-layl', 'The Night', 21),
    (93, 'al-ḍuḥā', 'The Forenoon', 11),
    (94, 'al-sharḥ', 'The Opening Forth', 8),
    (95, 'al-tīn', 'The Fig', 8),
    (96, 'al-ʿalaq', 'The Clot', 19),
    (97, 'al-qadr', 'The Night of Decree', 5),
    (98, 'al-bayyinah', 'The Clear Evidence', 8),
    (99, 'al-zalzalah', 'The Earthquake', 8),
    (100, 'al-ʿādiyāt', 'Those That Run', 11),
    (101, 'al-qāriʿah', 'The Striking Hour', 11),
    (102, 'al-takāthur', 'The Piling Up', 8),
    (103, 'al-ʿaṣr', 'Time', 3),
    (104, 'al-humazah', 'The Slanderer', 9),
    (105, 'al-fīl', 'The Elephant', 5),
    (106, 'quraysh', 'Quraysh', 4),
    (107, 'al-māʿūn', 'Small Kindnesses', 7),
    (108, 'al-kawthar', 'Abundance', 3),
    (109, 'al-kāfirūn', 'The Disbelievers', 6),
    (110, 'al-naṣr', 'The Help', 3),
    (111, 'al-masad', 'The Palm Fibre', 5),
    (112, 'al-ikhlāṣ', 'Sincerity', 4),
    (113, 'al-falaq', 'The Daybreak', 5),
    (114, 'al-nās', 'Mankind', 6),
]
SURAH_BY_ID = {row[0]: row for row in SURAHS}
AYAH_COUNTS = {row[0]: row[3] for row in SURAHS}
# Corpus v0.4 treebank coverage shown by the website navigation: chapters 1-8 and 59-114.
TREEBANK_CHAPTERS = set(range(1, 9)) | set(range(59, 115))
